Dsite/Dmap/urls.py
from django.urls import path

from . import views

app_name = 'Dmap'
# urlpatterns = [
# 	path('', views.index, name='index'),
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]
# urlpatterns = [
#     path('', views.IndexView.as_view(), name='index'),
#     path('<int:pk>/', views.DetailView.as_view(), name='detail'),
#     path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

urlpatterns = [
	path('', views.index, name='index'),
	path('routeInfo/', views.routeInfo, name='routeInfo'),
	path('locInfo/', views.locInfo, name='locInfo')

]

Dsite/Dsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('Dmap/', include('Dmap.urls')),
    path('admin/', admin.site.urls),
]

Dsite/Dmap/models.py
from django.db import models


# Create your models here.


# class UserLastLocation(models.Model):
	# user = models.ForeignKey()

class PictureLocation(models.Model):
	url = models.CharField(max_length=200)
	name = models.CharField(max_length=200)
	lat = models.FloatField(max_length=200)
	lng = models.FloatField(max_length=200)

Dsite/Dmap/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from .ntu_map_search import *
import googlemaps
from .models import PictureLocation

gmaps = googlemaps.Client(key="AIzaSyBOcaF80s4gu1xTbBxn7uRR9EU0ziTjhOs")


# from ntu_map_search import *
# Create your views here.
# def index(request):
# 	latest_question_list = Question.objects.order_by('-pub_date')[:5]
# 	output = ', '.join([q.question_text for q in latest_question_list])
# 	output += "Hi there :)"
# 	template = loader.get_template('polls/index.html')
# 	context = {
# 		'latest_question_list': latest_question_list
# 	}
# 	# return HttpResponse(template.render(context,request))
# 	return render(request, 'polls/index.html', context)
#
# def detail(request, question_id):
# 	# try:
# 	# 	question = Question.objects.get(pk=question_id)
# 	# except Question.DoesNotExist:
# 	# 	raise Http404("Question does not exist")
# 	question = get_object_or_404(Question, pk=question_id)
# 	return render(request, 'polls/detail.html', {'question': question})
# 	# return HttpResponse("You're looking at question %s." % question_id)
#
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

def routeInfo(request):
	print(request.POST)
	if request.method == 'POST':
		if 'start' in request.POST and \
				'end' in request.POST and \
				'mode' in request.POST:

			# Check if the route starts or end in NTU by coordinate
			start = request.POST['start']
			end = request.POST['end']
			mode = request.POST['mode']

			search_result = search(start, end, mode)

			locations = search_result[0]
			# print(type(locations))
			# print("HAHA")
			# print(locations)
			# locations = ",".join(locations)

			# print("after concantenation")
			# print(locations)
			# print(type(locations))
			#
			# print(locations)
			# print(type(output[1]))

			directions = search_result[1]
			landmarks_list, landmarks_coordinates = get_key_landmarks(directions)

			print("getting landmarks info")

			locations = ",".join(locations)
			directions = ",".join(directions)
			response = locations + "*" + directions +"*" + landmarks_list + "*" + landmarks_coordinates
			# response = locations
			# print(response)
			print("end of landmarks info")

			return HttpResponse(response)
		# Perform normal search from start until it
		# reaches entrance of NTU

		# if the route start and end at NTU
		# perform ntu map search
		# return HttpResponse(str(list))

		# to return directions..
		# return HttpResponse('success')
		else:
			return HttpResponse('nope..')

	else:
		return HttpResponse('nope..')


def locInfo(request):
	print(request.POST)
	if request.method == 'POST':
		if 'lat' in request.POST and 'lng' in request.POST:
			# Todo: Save to server for the latest location

			# Todo: Return previous location if necessary
			print("Hahahahahah")
			return HttpResponse('Success')
		else:
			return HttpResponse('Failed')


def index(request):
	context = {'testing': 100}

	return render(request, 'Dmap/index.html', context)


# context = {
# 		'latest_question_list': latest_question_list
# 	}

# def index(request):
# 	latest_question_list = Question.objects.order_by('-pub_date')[:5]
# 	output = ', '.join([q.question_text for q in latest_question_list])
# 	output += "Hi there :)"
# 	template = loader.get_template('polls/index.html')
# 	context = {
# 		'latest_question_list': latest_question_list
# 	}
# 	# return HttpResponse(template.render(context,request))
# 	return render(request, 'polls/index.html', context)
#


# def vote(request, question_id):
# 	question = get_object_or_404(Question, pk=question_id)
# 	try:
# 		selected_choice = question.choice_set.get(pk=request.POST['choice'])
# 	except (KeyError, Choice.DoesNotExist):
# 		# Redisplay the question voting form.
# 		return render(request, 'polls/detail.html', {
# 			'question': question,
# 			'error_message': "You didn't select a choice.",
# 		})
# 	else:
# 		selected_choice.votes += 1
# 		selected_choice.save()
# 		# Always return an HttpResponseRedirect after successfully dealing
# 		# with POST data. This prevents data from being posted twice if a
# 		# user hits the Back button.
# 		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

Dsite/Dmap/templates/Dmap/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'Dmap:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

Dsite/Dmap/templates/Dmap/index.html
{#{% csrf_token %}#}
{% load bootstrap4 %}
<!DOCTYPE html>


{% load static %}
<head>
    <script>
         //Test code to pass variable from django to javascript..
        var testing = {{testing}};
        console.log(testing);
        var route_url = "{% url 'Dmap:routeInfo' %}";
        var loc_url = "{% url 'Dmap:locInfo' %}";

        // {% static 'Dmap\images\NDC_to_NH\1.351272,103.688468.jpeg' %}


    </script>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="croppie.css" />
    <script src="croppie.js"></script>
    <!--<link rel="stylesheet" type="text/css" href="{% static 'Dmap/style.css' %}">-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script language="JavaScript"  src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'Dmap/index.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


</head>
<body>

    <div class="container">
        <form>
        <!--<div id="floating-panel">-->
            <div class="row">
                <div class="col-6">
                    <!--<label for="start">Start Location</label>-->
                    <input type="text" class="form-control" id="start" value="" placeholder="Start Location">
                </div>
                <div class="col-6">
                    <!--<label for="end">End Location</label>-->
                    <input type="text" class="form-control" id="end" value="" placeholder="End Location">
                </div>
            </div>
            <div class="row">
                <div class="col-8">
                <label for="mode">Mode of transport</label>
                <select class="form-control" id="mode">
                    <option value="d">Driving</option>
                    <option value="w">Walking</option>
                    <option value="t">Bicycling</option>
                    <option value="b">Transit</option>
                </select>
                </div>
                <div class="col-4">
                    <br>
                    <input class="form-control" type="button" id="go" value="Go">
                </div>
            </div>
        </form>
        <!--</div>-->
        <br>
        <div class="row">
            <div class="col-8">
                <div id="map" style="width:100%;height:400px"></div>
            </div>
            <div class="col-2">
                <ul class="list-group" id="directions" style="width:350px">
                  <!--<li class="list-group-item">Cras justo odio</li>-->
                  <!--<li class="list-group-item">Dapibus ac facilisis in</li>-->
                  <!--<li class="list-group-item">Morbi leo risus</li>-->
                  <!--<li class="list-group-item">Porta ac consectetur ac</li>-->
                  <!--<li class="list-group-item">Vestibulum at eros</li>-->
                </ul>
            </div>
        </div>

        <div class="row" id="card_segment">
            <div class="col-sm-4">
                <div class="card" id="card1">
                    <img class="card-img-top img-thumbnail rounded" src="{% static 'Dmap\images\NDC_to_NH\1.351272,103.688468.jpeg' %}">
                    <div class="card-body">
                        <h5 class="card-title"></h5>
                        <p class="card-text"></p>
                     </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card" id="card2">
                    <img class="card-img-top img-thumbnail rounded" src="..." alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <!--<a href="#" class="btn btn-primary">Go somewhere</a>-->
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card" id="card3">
                    <img class="card-img-top img-thumbnail rounded" src="..." alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <!--<a href="#" class="btn btn-primary">Go somewhere</a>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBOcaF80s4gu1xTbBxn7uRR9EU0ziTjhOs&callback=getMap"></script>
<script>
    hide_cards();
    updatePath();
</script>
<!--{% if latest_question_list %}-->
    <!--<ul>-->
    <!--{% for question in latest_question_list %}-->
        <!--<li><a href="{% url 'Dmap:detail' question.id %}">{{ question.question_text }}</a></li>-->
    <!--{% endfor %}-->
    <!--</ul>-->
<!--{% else %}-->
    <!--<p>No polls are available.</p>-->
<!--{% endif %}-->
</html>

Dsite/Dmap/templates/Dmap/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>